apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-web
  labels:
    app: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: http-server
  template:
    metadata:
      labels:
        app: http-server
    spec:
      containers:
      - name: http-server
        image: nginx:latest
        ports:
        - containerPort: 80
